server:
  port: 8085
spring:
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: 4mR9OIt3qadt22Dbbr5KC01lsRQ0qVcg
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: 4mR9OIt3qadt22Dbbr5KC01lsRQ0qVcg
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: 4mR9OIt3qadt22Dbbr5KC01lsRQ0qVcg
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka/
    register-with-eureka: false