server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: 4mR9OIt3qadt22Dbbr5KC01lsRQ0qVcg
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: 4mR9OIt3qadt22Dbbr5KC01lsRQ0qVcg