spring:
  cloud:
    gateway:
      routes:
        - id: catalogue-service-route
          uri: http://172.17.0.1:8081
          predicates:
            - Host=catalogue.api.selm.ag.172.17.0.1.nip.io
        - id: feedback-service-route
          uri: http://172.17.0.1:8084
          predicates:
            - Host=feedback.api.selm.ag.172.17.0.1.nip.io
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/selmag
        registration:
          discovery:
            provider: keycloak
            client-id: api-gateway
            client-secret: kaKBJ6Pc9mPldygbbI5SgWkZWo1ewk5y
            authorization-grant-type: client_credentials
            scope:
              - discovery
          metrics:
            provider: keycloak
            client-id: api-gateway
            client-secret: kaKBJ6Pc9mPldygbbI5SgWkZWo1ewk5y
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
  application:
    name: selmag-api-gateway
  boot:
    admin:
      client:
        url: http://172.17.0.1:8085
        instance:
          name: api-gateway
          service-host-type: ip
          service-base-url: http://172.17.0.1:8086
          management-base-url: http://172.17.0.1:8086
        enabled: true
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://172.17.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8086
  forward-headers-strategy: framework
eureka:
  client:
    enabled: false