scrape_configs:
  - job_name: selmag_admin_service
    static_configs:
      - targets: ["http://172.17.0.1:8085"]
        labels:
          application: selmag-admin-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: vTpeB59Sb2Qzh0HI4cXBlewm2ivY0dzD
      token_url: http://172.17.0.1:8082/realms/selmag/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: selmag_catalogue_service
    static_configs:
      - targets: ["http://172.17.0.1:8081"]
        labels:
          application: selmag-catalogue-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: vTpeB59Sb2Qzh0HI4cXBlewm2ivY0dzD
      token_url: http://172.17.0.1:8082/realms/selmag/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: selmag_feedback_service
    static_configs:
      - targets: ["http://172.17.0.1:8084"]
        labels:
          application: selmag-feedback-service
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: vTpeB59Sb2Qzh0HI4cXBlewm2ivY0dzD
      token_url: http://172.17.0.1:8082/realms/selmag/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: selmag_customer_app
    static_configs:
      - targets: ["http://172.17.0.1:8083"]
        labels:
          application: selmag-customer-app
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: vTpeB59Sb2Qzh0HI4cXBlewm2ivY0dzD
      token_url: http://172.17.0.1:8082/realms/selmag/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials
  - job_name: selmag_manager_app
    static_configs:
      - targets: ["http://172.17.0.1:8080"]
        labels:
          application: selmag-manager-app
    metrics_path: /actuator/prometheus
    oauth2:
      client_id: victoria-metrics
      client_secret: vTpeB59Sb2Qzh0HI4cXBlewm2ivY0dzD
      token_url: http://172.17.0.1:8082/realms/selmag/protocol/openid-connect/token
      scopes:
        - metrics
      endpoint_params:
        grant_type: client_credentials