selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      username: catalogue_service_user
      password: password
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager