image: 192.168.49.1:5000/selmag/catalogue-service:24.1.1
vmagent:
  image: victoriametrics/vmagent:v1.93.12
  remoteWrite:
    url: http://vm-svc.selmag.svc.cluster.local:8428/api/v1/write
ingress:
  host: catalogue.api.selm.ag.192.168.49.2.nip.io