apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-vmagent-cm
data:
  promscrape.yaml: |
    scrape_configs:
      - job_name: selmag_manager_app
        static_configs:
          - targets: ["http://localhost:8080"]
            labels:
              application: selmag-manager-app
        metrics_path: /actuator/prometheus
        oauth2:
          client_id: victoria-metrics
          client_secret: vTpeB59Sb2Qzh0HI4cXBlewm2ivY0dzD
          token_url: http://keycloak.selm.ag.192.168.49.2.nip.io/realms/selmag/protocol/openid-connect/token
          scopes:
            - metrics
          endpoint_params:
            grant_type: client_credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selmag-manager-app-deployment
  labels:
    app: selmag-manager-app
spec:
  selector:
    matchLabels:
      app: selmag-manager-app
  template:
    metadata:
      labels:
        app: selmag-manager-app
    spec:
      volumes:
        - name: vmconfig
          configMap:
            name: manager-vmagent-cm
        - name: service-config
          configMap:
            name: manager-app-config
      containers:
        - name: selmag-manager-app
          image: 192.168.49.1:5000/selmag/manager-app:24.1.1
          args:
            - --spring.config.import=/etc/opt/manager-app/application-k8s.yml
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: LOKI
              value: http://loki-svc.selmag.svc.cluster.local:3100
          volumeMounts:
            - mountPath: /etc/opt/manager-app
              name: service-config
        - name: vmagent
          image: victoriametrics/vmagent:v1.93.12
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - -promscrape.config=/etc/opt/vmagent/promscrape.yaml
            - -remoteWrite.url=http://vm-svc.selmag.svc.cluster.local:8428/api/v1/write
            - -remoteWrite.label=instance=$(NODE_NAME)
          volumeMounts:
            - mountPath: /etc/opt/vmagent
              name: vmconfig
---
apiVersion: v1
kind: Service
metadata:
  name: selmag-manager-app-svc
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: selmag-manager-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selmag-manager-app-ingress
spec:
  rules:
    - host: manager.selm.ag.192.168.49.2.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: selmag-manager-app-svc
                port:
                  name: http