server:
  port: 8084
spring:
  application:
    name: selmag-feedback-service
  boot:
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: feedback-service
          service-host-type: ip
        enabled: true
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8082/realms/selmag
      client:
        registration:
          keycloak:
            client-id: feedback-service
            client-secret: 4cD79sTpV318BqiIWWUYsfjywdzg4DeK
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: feedback-service
            client-secret: 4cD79sTpV318BqiIWWUYsfjywdzg4DeK
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/selmag
springdoc:
  swagger-ui:
    oauth:
      client-id: feedback-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
keycloak:
  uri: http://localhost:8082
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://172.17.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    enabled: false