server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag